### ISSUE TITLE
PPL- Homework week 1

### ISSUE THREAD

**Issue by phuongvietvu0306** [congnv8192/2015_ppl_3c13_group4#3]
// Share homework week 1 vs mng có gì chia sẻ & tham khao nhé :)
import java.util.Scanner;
import java.util.Random;

public class week_1
{
   public static void Ex2_1()
   {
      System.out.println();
      System.out.println("           *****\*           ************\*        *********_");
      System.out.println("           *_    *\*                *\*            *_");
      System.out.println("           *_     *\*               *\*            *_");
      System.out.println("           *_      *\*              *\*            *_");
      System.out.println("           *_      *\*              *\*            *******_");
      System.out.println("           *_      *\*       *\*     *\*            *_");
      System.out.println("           *_     *\*         *\*    *\*            *_");
      System.out.println("           *_    *\*           *\*  *\*             *_");
      System.out.println("           *_**\*               ***\*              **********");
      System.out.println();
   }

   public static void Ex2_2()
   {
      Random rand = new Random();

```
  int firstDice = rand.nextInt(6)+1;
  int secDice = rand.nextInt(6)+1;
  int total= firstDice + secDice;

  System.out.println("The first dice rolls: " +firstDice);
  System.out.println("The second dice rolls: " +secDice);
  System.out.println("The total roll is: " + total);
```

   }

   public static void Ex2_3()
   {
      System.out.println("Enter your name: ");
      String name = new Scanner(System.in).nextLine();

```
  System.out.println("Hello "+name.toUpperCase()+" nice to meet you!");
```

   }

   public static void Ex2_4()
   {
      System.out.println("How many quarter do you have?");
      int quart  = new Scanner(System.in).nextInt();

```
  System.out.println("How many dimes do you have?");
  int dime  = new Scanner(System.in).nextInt();

  System.out.println("How many nickles do you have?");
  int nick  = new Scanner(System.in).nextInt();

  System.out.println("How many pennies do you have?");
  int pen  = new Scanner(System.in).nextInt();

  double total = quart*0.25 + dime*0.10 + nick*0.05 + pen*0.01;
  System.out.println("You has "+ total+" dollars");
```

   }

   public static void Ex2_5()
   {
      System.out.println("How many egg do you have?");
      int egg = new Scanner(System.in).nextInt();
      int gross = egg/144;
      int dozen= (egg%144)/12;
      int left = dozen%12;
      System.out.printf("You have %d gross, %d dozen, and %d eggs \n", gross, dozen, left);
   }

   public static void Ex2_6()
   {
      System.out.println("Enter your first & last name:");
      String name = new Scanner(System.in).nextLine();
      int space = name.indexOf(" ");

```
  String firstName= name.substring(0, space);
  String lastName= name.substring(space+1);

  System.out.printf("Your first name is: %c%s, which has %d characters \n", firstName.toUpperCase().charAt(0), firstName.substring(1) , firstName.length());
  System.out.printf("Your first name is: %c%s, which has %d characters \n", lastName.toUpperCase().charAt(0), lastName.substring(1), lastName.length());
  System.out.printf("Your initials are: %c%c \n", firstName.toUpperCase().charAt(0), lastName.toUpperCase().charAt(0) );
```

   }

   public static void main(String args[])
   {
      Ex2_1();
      Ex2_2();
      Ex2_3();
      Ex2_4();
      Ex2_5();
      Ex2_6();
   }
}

**Comment by congnv8192** [comment]
Nice,
Please read this then upload and share them in your own folder
http://fit.hanu.edu.vn/fitportal/mod/resource/view.php?id=9053

Best,

On Wed, Mar 25, 2015 at 10:02 PM, phuongvietvu0306 <notifications@github.com
